export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';

export const GET_AS_SEEN_ON = 'GET_AS_SEEN_ON';
export const GET_AS_SEEN_ON_SUCCESS = 'GET_AS_SEEN_ON_SUCCESS';
export const GET_AS_SEEN_ON_FAILURE = 'GET_AS_SEEN_ON_FAILURE';

export const GET_PARTNER = 'GET_PARTNER';
export const GET_PARTNER_SUCCESS = 'GET_PARTNER_SUCCESS';
export const GET_PARTNER_FAILURE = 'GET_PARTNER_FAILURE';